# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Release new Python Package

on:
  workflow_dispatch:
  release:
    types: [published]


permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |        
        python -m pip install --upgrade pip
        pip install build==0.10.0 wget numpy SimpleITK twine
    - name: Build package
      run: |
        python setup_prepare.py --linux --download -v v2023.10.6
        python -m build
        mv dist/m2aia-0.5.2-py3-none-any.whl dist/m2aia-0.5.2-py3-none-manylinux_2_31_x86_64.whl
        python setup_prepare.py --windows --download -v v2023.10.8
        python -m build
        mv dist/m2aia-0.5.2-py3-none-any.whl dist/m2aia-0.5.2-py3-none-win-amd64.whl
        python setup_prepare.py --windows --linux -v v2023.10.6
        python -m build
        rm dist/m2aia-0.5.2-py3-none-any.whl
    - name: Publish package
      run: |
        run: |
        cat <<- EOF > $HOME/.pypirc
          [pypi]
          username: __token__
          password: ${{ secrets.GH_ACTION_PYPI }}
        EOF
        python -m twine upload dist/*
      
